name: docker-complex

on:
  push:
    branches:
      - main
  workflow_dispatch: # Put here!!

defaults:
  run:
    working-directory: './'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - run: docker build -t joconstantine/react-test -f ./client/Dockerfile.dev ./client
      # - run: docker run -e CI=true joconstantine/react-test npm test -- --coverage

      - name: Build and push - client
        id: docker_build_client
        uses: docker/build-push-action@v2
        with:
          context: client
          push: true
          tags: joconstantine/multi-client

      - name: Build and push - nginx
        id: docker_build_nginx
        uses: docker/build-push-action@v2
        with:
          context: nginx
          push: true
          tags: joconstantine/multi-nginx

      - name: Build and push - server
        id: docker_build_server
        uses: docker/build-push-action@v2
        with:
          context: server
          push: true
          tags: joconstantine/multi-server

      - name: Build and push - worker
        id: docker_build_worker
        uses: docker/build-push-action@v2
        with:
          context: worker
          push: true
          tags: joconstantine/multi-worker
