name: docker-complex

on:
  push:
    branches:
      - main
  workflow_dispatch: # Put here!!

defaults:
  run:
    working-directory: './'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: actions/checkout@v2
      # - run: docker build -t joconstantine/react-test -f ./client/Dockerfile.dev ./client
      # - run: docker run -e CI=true joconstantine/react-test npm test -- --coverage
      # - run: docker build -t joconstantine/multi-client ./client
      # - run: docker build -t joconstantine/multi-nginx ./nginx
      # - run: docker build -t joconstantine/multi-server ./server
      # - run: docker build -t joconstantine/multi-worker ./worker
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: client
          push: true
          tags: joconstantine/multi-client
      # - run: docker push joconstantine/multi-client
      # - run: docker push joconstantine/multi-nginx
      # - run: docker push joconstantine/multi-server
      # - run: docker push joconstantine/multi-worker
